import 'package:flutter/material.dart';
final problemNameCard = ValueNotifier<bool>(false);
String problemCode = "...";
String? problemLevel = "...";
String problemName = "...";
String problemDiv = "...";
String problemLink = "...";
String? platform = "...";
bool externalWorksheet = true;
var worksheetNames;